[package]
name = "net2"
version = "0.2.7"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/alexcrichton/net2-rs"
homepage = "https://github.com/alexcrichton/net2-rs"
documentation = "http://alexcrichton.com/net2-rs"
description = """
Extensions to the standard library's networking types as proposed in RFC 1158.
"""

[dependencies]
libc = "0.1"
ws2_32-sys = "0.1"
winapi = "0.2"
kernel32-sys = "0.1"
cfg-if = "0.1"

[features]
nightly = []
